server:
  port: 9032

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

spring:
  application:
    name: product-web
  thymeleaf:
    cache: false
    mode: LEGANCYHTML5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

