
server:
  port: 9010

spring:
  application:
    name: cart-web
  redis:
      host: 192.168.127.128
      port: 6379
      jedis:
        pool:
          max-active: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

