server:
  port: 8770
spring:
  application:
    name: zuul
  thymeleaf:
    cache: false
    mode: LEGANCYHTML5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
#    static:
#      path: /static/**
#      url: http://localhost:8770/static/
    index:
      path: /**
      serviceId: index-web
#      stripPrefix: false
    search:
      path: /search/**
      serviceId: search-web
      stripPrefix: false
    desc:
      path: /desc/**
      serviceId: product-web
      stripPrefix: false

    shopcart:
      path: /user/cart/**
      serviceId: cart-web
      stripPrefix: false
#    static:
#      path: /static/**
#      url: http://localhost:9010/static/
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 10000   #socket超时

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000