server:
  port: 8770
spring:
  application:
    name: zuul
  thymeleaf:
    cache: false
    mode: LEGANCYHTML5
  resources:
    chain:
      cache: false
      enabled: false
    cache:
      period: 1800

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
#    static:
#      path: /**
#      url: http://localhost:8770/**
    index:
      path: /**
      serviceId: index-web
#      stripPrefix: false
    search:
      path: /search/**
      serviceId: search-web
      stripPrefix: false
    desc:
      path: /desc/**
      serviceId: product-web
      stripPrefix: false
    order:
      path: /order/desc/**
      serviceId: order-web
      stripPrefix: false
    address:
      path: /address/add/**
      serviceId: address-web
      stripPrefix: false

    shopcart:
      path: /user/cart/**
      serviceId: cart-web
      stripPrefix: false
#    static:
#      path: /static/**
#      url: http://localhost:8770/


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000