
spring:
  application:
    name: goods-service
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8020
