spring:
  application:
    name: back-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9020

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.241.131:22122
image:
  server: http://192.168.241.131/
#spring:
#  rabbitmq:
#    host: 192.168.241.131
#    port: 5672
#    username: zzp
#    password: 123
#    virtual-host: /zzp
