server:
  port: 9030

spring:
  application:
    name: search-web
  thymeleaf:
    cache: false
    mode: LEGANCYHTML5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#feign:
#  httpclient:
#    connection-timeout: 10000