server:
  port: 8031
spring:
  application:
    name: index-service
  datasource:
    url: jdbc:mysql://localhost:3306/shop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
