server:
  port: 9034

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

spring:
  application:
    name: address-web
  thymeleaf:
    cache: false
    mode: LEGANCYHTML5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
