server:
  port: 8034
spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/shop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
