server:
  port: 9001

spring:
  application:
    name: sso-web

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#  datasource:
#    url: jdbc:mysql://localhost:3306/shop?serverTimezone=GMT
#    username: root
#    password: root
#  redis:
#    host: 192.168.174.128
#    port: 6688
#    jedis:
#      pool:
#        max-active: 20

  # wgf 的配置
  datasource:
    url: jdbc:mysql://localhost:3306/shop
  redis:
    cluster:
      nodes: 192.168.116.131:6379,192.168.116.131:6380,192.168.116.131:6381,192.168.116.131:6382,192.168.116.131:6383,192.168.116.131:6384




