spring:
  application:
    name:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=GMT
    username: root
    password: root
  redis:
    host: 192.168.174.128
    port: 6688
    jedis:
      pool:
        max-active: 20
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


