spring:
  rabbitmq:
    host: 192.168.174.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  application:
    name: register-service
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=GMT
    username: root
    password: root
  redis:
    host: 192.168.174.128
    port: 6688
    jedis:
      pool:
        max-active: 20
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

